package Input

Keyboard := {
    device := InputDevice(),

    A := InputKey(4),
    B := InputKey(5),
    C := InputKey(6),
    D := InputKey(7),
    E := InputKey(8),
    F := InputKey(9),
    G := InputKey(10),
    H := InputKey(11),
    I := InputKey(12),
    J := InputKey(13),
    K := InputKey(14),
    L := InputKey(15),
    M := InputKey(16),
    N := InputKey(17),
    O := InputKey(18),
    P := InputKey(19),
    Q := InputKey(20),
    R := InputKey(21),
    S := InputKey(22),
    T := InputKey(23),
    U := InputKey(24),
    V := InputKey(25),
    W := InputKey(26),
    X := InputKey(27),
    Y := InputKey(28),
    Z := InputKey(29),

    _1 := InputKey(30),
    _2 := InputKey(31),
    _3 := InputKey(32),
    _4 := InputKey(33),
    _5 := InputKey(34),
    _6 := InputKey(35),
    _7 := InputKey(36),
    _8 := InputKey(37),
    _9 := InputKey(38),
    _0 := InputKey(39),

    Return := InputKey(40),
    Escape := InputKey(41),
    Backspace := InputKey(42),
    Tab := InputKey(43),
    Space := InputKey(44),

    Minus := InputKey(45),
    Equals := InputKey(46),
    LeftBracket := InputKey(47),
    RightBracket := InputKey(48),
    Backslash := InputKey(49), 
    Semicolon := InputKey(51),
    Apostrophe := InputKey(52),
    Grave := InputKey(53),
    Comma := InputKey(54),
    Period := InputKey(55),
    Slash := InputKey(56),

    Capslock := InputKey(57),

    F1 := InputKey(58),
    F2 := InputKey(59),
    F3 := InputKey(60),
    F4 := InputKey(61),
    F5 := InputKey(62),
    F6 := InputKey(63),
    F7 := InputKey(64),
    F8 := InputKey(65),
    F9 := InputKey(66),
    F10 := InputKey(67),
    F11 := InputKey(68),
    F12 := InputKey(69),

    PrintScreen := InputKey(70),
    ScrollLock := InputKey(71),
    Pause := InputKey(72),
    Insert := InputKey(73),    
    Home := InputKey(74),
    PageUp := InputKey(75),
    Delete := InputKey(76),
    End := InputKey(77),
    PageDown := InputKey(78),
    Right := InputKey(79),
    Left := InputKey(80),
    Down := InputKey(81),
    Up := InputKey(82),

    NumlockClear := InputKey(83),
                                 
    KP_Divide := InputKey(84),
    KP_Multiply := InputKey(85),
    KP_Minus := InputKey(86),
    KP_Plus := InputKey(87),
    KP_Enter := InputKey(88),
    KP_1 := InputKey(89),
    KP_2 := InputKey(90),
    KP_3 := InputKey(91),
    KP_4 := InputKey(92),
    KP_5 := InputKey(93),
    KP_6 := InputKey(94),
    KP_7 := InputKey(95),
    KP_8 := InputKey(96),
    KP_9 := InputKey(97),
    KP_0 := InputKey(98),
    KP_Period := InputKey(99),
}